import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { ThemeProvider } from "@/context/theme-provider";
import Nav from "@/components/Nav/Nav";
import { SimpleFooter } from "@/components/Footer/Footer";
import RightPanel from "./_components/RightPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex min-h-screen w-full">
              <AppSidebar />

              <div className="flex flex-1 flex-col overflow-hidden">
                <Nav>
                  <SidebarTrigger />
                </Nav>

                <main className="flex-1 overflow-auto p-4 md:p-6 lg:p-8">
                  <div className="grid grid-cols-1 lg:grid-cols-[1fr_200px] xl:grid-cols-[1fr_240px] 2xl:grid-cols-[1fr_280px] gap-6 max-w-7xl mx-auto">
                    {" "}
                    {/* Main Content */}
                    <div className="min-w-0">{children}</div>
                    {/* Right Panel */}
                    <aside className="hidden lg:block">
                      <RightPanel />
                    </aside>
                  </div>
                </main>

                <SimpleFooter />
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
